# Generated by Django 3.0.8 on 2021-06-15 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="MenuOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.Food"
                    ),
                ),
                (
                    "id_menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.Menu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("comments", models.CharField(max_length=100)),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.MenuOption",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="foods",
            field=models.ManyToManyField(through="menu.MenuOption", to="menu.Food"),
        ),
    ]
