# Generated by Django 3.0.8 on 2021-06-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_auto_20210615_1419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
