# Generated by Django 3.0.8 on 2021-06-18 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_auto_20210617_0759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
